# Generated by Django 3.1.1 on 2020-09-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coordinate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="RequestHistory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("request", models.CharField(max_length=2000)),
            ],
        ),
    ]
