# Generated by Django 3.1.1 on 2020-09-17 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0002_auto_20200916_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesthistory',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 17, 11, 21, 41, 113408)),
        ),
    ]
