# Generated by Django 3.1.1 on 2020-09-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0004_auto_20200917_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesthistory',
            name='x_axes',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='y_axes',
            field=models.FloatField(default=0),
        ),
    ]
