# Generated by Django 3.1.1 on 2020-09-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0005_auto_20200917_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesthistory',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
