# Generated by Django 3.1.1 on 2020-09-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0006_requesthistory_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesthistory',
            name='action',
            field=models.CharField(default='N/A', max_length=300),
        ),
    ]
