# Generated by Django 3.1.1 on 2020-09-18 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0007_requesthistory_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requesthistory',
            old_name='action',
            new_name='operation',
        ),
    ]
